version: '3.1'

services:
  db:
    container_name: APM_manager
    image: postgres:9.6.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=apm_manager